name: "ðŸš€ CI Build and Deploy"

on:
  push:
    branches:
      - main
  
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci-pypi-publish:
    name: ci-pypi-publish
    runs-on: ubuntu-latest
    
    steps:
      - name: "Check if this is a doc branch"
        run: |
          if [[ ${{ github.ref }} == refs/heads/docs/* || ${{ github.ref }} == refs/heads/docs-* ]]; then
            echo "Branch starts with 'docs/' - Skipping workflow"
            exit 0
          fi
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Package Build
        run: |
          pip install --upgrade build
          python -m build

      - name: PyPI Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  update-release-draft:
    name: update-relase-draft
    runs-on: ubuntu-latest

    steps:
      - name: "Check if this is a doc branch"
        run: |
          if [[ ${{ github.ref }} == refs/heads/docs/* || ${{ github.ref }} == refs/heads/docs-* ]]; then
            echo "Branch starts with 'docs/' - Skipping workflow"
            exit 0
          fi

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: configs/release-drafter.yml     
