name: "âš™ï¸ CI feature branch"

on:
  push:
    branches:
      - feature**
      - '[0-9].[0-9].x'
      - 'v[0-9].[0-9].[0-9]'
      - 'v[0-9].[0-9].x'
      - docs**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci-python:
    name: ci-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Dependencies Setup
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt
      
      - name: Linter Analysis - flake8
        run:
          flake8 . --ignore E501
  
  ci-pytest:
    name: ci-pytest
    runs-on: ubuntu-latest
    needs:
      - ci-python

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Dependencies Setup
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt

      - name: Unit Test with pytest
        run:
          pytest -vv --color=yes --cov=./ --cov-report=xml

      - name: Test Coverage with Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  open-pr-to-main:
    name: open-pr-to-main
    runs-on: ubuntu-latest
    needs:
      - ci-pytest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PR to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref }}
          destination_branch: "main"
          pr_title: "pr(main): ${{ github.ref }} -> main"
          pr_template: ".github/pull_request_template.md"
          pr_assignee: "ThiagoPanini"
          pr_label: "github-bot ðŸ¤–"
          github_token: ${{ secrets.GITHUB_TOKEN }}
